### ISSUE TITLE
学习3d立方体的解坑笔记

### ISSUE THREAD

**Issue by skykobe** [skykobe/skykobe.github.io#9]
## 在页面构造一个立方体，加上一些自己有趣的思维，可以做出很多有趣的网页。

首先，我们残暴的直接看代码：
#### CSS

``` CSS
.container {   /* 包含我们的立方体 */
    width: 200px;
    height: 200px;
    padding: 0px;
    position: relative;
    margin: 50px auto 40px;
    perspective: 1000px;
    transform: translateZ( -100px );      
}   
#cube {  /*我们的正方体*/
    width: 100%;
    height: 100%;
    position: absolute;
    transform-style: preserve-3d;
    transition: 1s;
}
#cube figure {   /*正方体的面*/
    width: 196px;
    height: 196px;
    display: block;
    position: absolute;
    border: 2px solid gray;
    margin: 0px;  /* *1：这里要注意！！！*/
}  
#cube .front  {  /* 形成正面的变换 */
    transform: rotateY(0deg) translateZ( 100px );  /* *2：这里要注意*/
    background: rgba(0,0,0, 0.5);
    text-align: center;
    color: white
}
#cube .back   { /* 形成背面的变换 */
    transform: rotateX( 180deg ) translateZ( 100px );
    background: rgba(20,255,255, 0.5);
    text-align: center;
}
#cube .right  {  /* 形成右面的变换 */
    transform: rotateY(  90deg ) translateZ( 100px );
    background: rgba(222,184,135, 0.5);
    text-align: center;
}
#cube .left   { /* 形成左面的变换 */
    transform: rotateY( -90deg ) translateZ( 100px );
    background: rgba(169,169,169, 0.5);
    text-align: center;
}
#cube .top    {  /* 形成顶面的变换 */
    transform: rotateX(  90deg ) translateZ( 100px );
    background: rgba(255,140,0, 0.5);
    text-align: center;
}
#cube .bottom {  /* 形成底面的变换 */
    transform: rotateX( -90deg ) translateZ( 100px );
    background: rgba(0,206,209, 0.5);
    text-align: center;
} 
```

【图片】
这样，一个立方体就出来了，现在解释其中的两点坑（要点）：

<h3> 1.  在CSS的`#cube figure`中我特意设置了margin，这里就涉及到这个H5新标签自带的margin值了，</h3>

【图片】

<h3>打开控制台，我们查看该正方体里边的内容布局，可以看出，因为figure自身margin的原因，图形移位了，部分图形显示于container外，这时候，我们进行旋转特效时，就会导致旋转移位。
所以，直接`margin：0`消除改影响 </h3>
